name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out your repository
        uses: actions/checkout@v3
      
      - name: Setup Idris
        uses: sergeyshpadyrev/setup-idris@v1.2

      - name: Run a one-line script
        run: idris --version
        
      - name: Run a multi-line script
        run: idris2 --install trifunctors.ipkg
